### ISSUE TITLE
Migrate to new Twitter feed before  July 27, 2018

### ISSUE THREAD

**Issue by magdmartin** [OpenRefine/openrefine.github.com#28]
The twitter widget we are using will be deprecated on July 27, 2018. See [announcement](https://twittercommunity.com/t/deprecating-widget-settings/102295).  

Twitter offer no out of box widget to show result from a specific query. Easy option are either:
* List [tweets from @OpenRefine](https://dev.twitter.com/web/embedded-timelines/user)
* List [tweets with the tag #OpenRefine](https://dev.twitter.com/web/embedded-timelines/search)

If we want to keep the same feed we need to write our own widget using Twitter API.

**Comment by thadguidry** [comment]
Twitter apps and integration into Windows, Ubuntu, Mac, is much better than it was even 2 years ago.  I see no reason to present our Twitter feed into our pages, since most users get the feed on devices, phones, OS's, etc. and not through our HTML pages.  Just providing the Twitter logo and URL for our feed is "good enough".

-1 No need for our own widget
+1 kill the Twitter feed on our HTML pages.  Users get our feed through other means that are much more convenient to them.

**Comment by magdmartin** [comment]
new website deployed without twitter feed
